<a href="https://colab.research.google.com/github/akybharat/DL-PyTorch/blob/main/1_PyTorchOfficial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

### Tesor Basic Operations

In [ ]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [ ]:
tensor=torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [ ]:
if torch.cuda.is_available():
    tensor=tensor.to('cuda')
    print(tensor.device)

In [ ]:
tensor=torch.ones(4,4)
tensor[:,1]=0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
tensor.T

tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
tensor @tensor.T

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

###  INTRODUCTION TO TORCH.AUTOGRAD

torch.autograd is PyTorch differentiation engine.

In [ ]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model=resnet18(weights=ResNet18_Weights.DEFAULT)

data=torch.rand(1, 3, 64, 64)
labels=torch.rand(1, 1000)

prediction=model(data)


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████| 44.7M/44.7M [00:00<00:00, 108MB/s]


In [ ]:
loss=(prediction-labels).sum()

loss.backward()

In [ ]:
optim=torch.optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

optim.step()

Freezing part of NN

In [ ]:
from torch import nn, optim
model=resnet18(weights=ResNet18_Weights.DEFAULT)

for param in model.parameters():
    param.requires_grad=True

model.fc=nn.Linear(512, 10)
optimizer=optim.SGD(model.parameters(), lr=1e-2, momentum=0.9)

#### Building NN

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__():
    self.conv1=nn.Conv2d(1, 6, 5)
    self.conv2=nn.Conv2d(6, 16, 5)
    self.fc1=nn.Linear(16*5*5, 120)
    self.fc2=nn.Linear(120, 84)
    self.fc3=nn.Linear(84, 10)

  def forward(self, x):
    x=F.max_pool2d(F.relu(self.conv1(x)), (2,2))
    x=F.max_pool2d(F.relu(self.conv1(x)), 2)
    x=torch.flatten(x, 1)
    x=F.relu(self.fc1(x))
    x=F.relu(self.fc2(x))
    x=self.fc3(x)
    return x



In [ ]:
criterion = nn.MSELoss()
net=Net()

target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
input1 = torch.randn(1, 1, 32, 32)

import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input1)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update

### Training a Classifier